#!/usr/bin/env bash

USAGE='See https://github.com/popmedic/bash-ioslog/blob/master/README.md'

set -e

# Script arguments
argc=$#
argv=$@

# Terminal colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Make sure the user has `cfgutil`
if [[ -z $(which cfgutil) ]]; then
    echo -e "${RED}please install cfgutil using Configurator 2.  
Instructions are here: https://support.apple.com/en-ca/guide/apple-configurator-2/cad856a8ea58/mac${NC}" >&2
    exit 1
fi

# Get a list of all the devices
dvcs=$(cfgutil list)
cnt=${#dvcs[@]}

# Make sure the device exists
if [[ -z ${dvcs[0]} ]]; then 
    echo -e "${RED}No devices attached${NC}" >&2
    exit 1
fi

# Only one device, just start
if [[ ${cnt} == 1 ]]; then
    echo -e "${GREEN}only one device${NC}" >&2
    dvc=${dvcs[0]}
else
    # No index yet, select the device
    if [[ -z ${idx} ]]; then
        echo -e "
${GREEN}which device?${NC}

 index | device
-------|--------" >&2
        for (( idx=0; idx<${cnt}; idx++ )); do
            echo -e "   ${GREEN}${idx}${NC}   | ${dvcs[$idx]}" >&2
        done
        echo >&2
        read -p "index> " idx
        echo >&2
    fi
    # Make sure the index is in range
    if [[ -z "${idx##*[!0-9]*}" || ${idx} -ge ${cnt} ]]; then
        echo -e "${RED}index ${idx} out of range ${cnt}${NC}"
        exit 1
    fi
    # Set the device based on the index
    dvc=${dvcs[$idx]}
fi

# Get the ECID
ecid=$(echo ${dvc} | pcregrep -o1 "ECID: (0x[0-9A-F]+) ")
name=$(echo ${dvc} | pcregrep -o1 "Name: (.+)")
echo -e "${GREEN}syslog for ${name} with ECID of ${ecid}.${NC}" >&2

# See if we are using a pcre
if [[ $argc > 0 ]]; then
    # Make sure pcregrep is installed
    if [[ -z $(which pcregrep) ]]; then
        echo -e "${RED}pcregrep  required${NC}\n>>> install with brew:\n   brew install pcre" >&2
        exit 1
    fi
    echo -e "${GREEN}using pcregrep arguments: ${NC}$argv\n" >&2

    # Print the log with pcre
    cfgutil --ecid ${ecid} syslog | pcregrep $argv
fi

# Print the log
echo >&2
cfgutil --ecid ${ecid} syslog
