#!/usr/bin/env bash

# USAGE: See https://github.com/popmedic/bash-ioslog/blob/master/README.md

set -e

# Exit Codes
success=0
no_cfgutil=101
no_devices=102
index_out_of_range=103
index_unparsable=104
no_pcre=105

# Script arguments
argc=$#
argv=$@

# Terminal colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Make sure the user has `cfgutil`
if [[ -z $(which cfgutil) ]]; then
    echo -e "${RED}please install cfgutil using Configurator 2.  
Instructions are here: https://support.apple.com/en-ca/guide/apple-configurator-2/cad856a8ea58/mac${NC}" >&2
    exit ${no_cfgutil}
fi

# Get a list of all the devices
dvcs=$(cfgutil list)
cnt=${#dvcs[@]}

# Make sure the device exists
if [[ -z ${dvcs[0]} ]]; then 
    echo -e "${RED}No devices attached${NC}" >&2
    exit ${no_devices}
fi

# Only one device, just start
if [[ ${cnt} == 1 ]]; then
    echo -e "${GREEN}only one device${NC}" >&2
    dvc=${dvcs[0]}
else
    # No index yet, select the device
    if [[ -z ${idx} ]]; then
        echo -e "
${GREEN}which device?${NC}

 index | device
-------|--------" >&2
        for (( idx=0; idx<${cnt}; idx++ )); do
            echo -e "   ${GREEN}${idx}${NC}   | ${dvcs[$idx]}" >&2
        done
        echo >&2
        read -p "index> " idx
        echo >&2
    fi
    # Make sure the index is in range
    if [[ -z "${idx##*[!0-9]*}" || ${idx} -ge ${cnt} ]]; then
        echo -e "${RED}index ${idx} out of range ${cnt}${NC}"
        exit ${index_out_of_range}
    fi
    # Set the device based on the index
    dvc=${dvcs[$idx]}
fi

# Get the ECID
ecid=$(echo ${dvc} | pcregrep -o1 "ECID: (0x[0-9A-F]+) ")
name=$(echo ${dvc} | pcregrep -o1 "Name: (.+)")
if [[ -z ${ecid} || -z ${name} ]]; then
    echo -e "${RED}index ${idx} in devices ${dvcs} is not parsable${NC}"
    exit ${index_unparsable}
fi
echo -e "${GREEN}syslog for ${name} with ECID of ${ecid}.${NC}" >&2

# trap sigint for error handling
trap ctrl_c SIGINT
function ctrl_c {
    exit ${success}
}

# See if we are using a pcre
if [[ $argc > 0 ]]; then
    # Make sure pcregrep is installed
    if [[ -z $(which pcregrep) ]]; then
        echo -e "${RED}pcregrep required${NC}
>>> install with brew:
    brew install pcre" >&2
        exit ${no_pcre}
    fi
    echo -e "${GREEN}using pcregrep arguments: ${NC}$argv\n" >&2

    # Print the log with pcre
    cfgutil --ecid ${ecid} syslog | pcregrep $argv
else
    # Print the log
    echo >&2
    cfgutil --ecid ${ecid} syslog
fi
